
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: library
  password: Incorrect12

development:
  adapter: postgresql
  database: rails_react_development
  username: library
  password: Incorrect12
  encoding: unicode
  host: localhost
  pool: 5

test:
  adapter: postgresql
  database: rails_react_test
  username: library
  password: Incorrect12
  encoding: unicode
  host: localhost
  pool: 5

production:
  <<: *default
  database: rails_react_production
  username: library
  password: <%= ENV["RAILS_REACT_DATABASE_PASSWORD"] %>
